### ISSUE TITLE
小田さんからのDM&安否確認メールに対応可能でしたらお願いします

### ISSUE THREAD

**Issue by hansuoi** [hansuoi/shibuya#2]
部長&私との3人DMに来ている通り、安否確認の連絡待ちなので、
対応可能でしたらお願いしたいですーm(_ _)m

**Comment by hansuoi** [comment]
GitHubのメール通知をつけている可能性に賭けるぜ

**Comment by hansuoi** [comment]
あと、これに気が付いていただけてたら、藤崎さん・井畑さん・田村さんにも同様の連絡が行っているので、伝言をお願いしたいです。

**Comment by YushiroDodo63** [comment]
@hansuoi 
今確認しました！
出先なのですが数分後にはDMの方にも返信致します🙇‍♂️
他メンバーにもお伝えしておきますね🙆‍♂️

**Comment by hansuoi** [comment]
@YushiroDodo63 
ありがとうございます！よろしくお願いします🙇‍♂️🙇‍♂️

**Comment by Schwarzschi1d** [comment]
@hansuoi 
確認遅くなり申し訳ございません。
北海道に帰省しているので肉体は無事です。が、PCを新潟に置いて行ってるためDM対応ができません。
今後もこのスレッドで連絡させてください（メール通知は奇跡的にオンでした）。

PCの安否（落下等で故障してないか）は今月14日に確認できる予定です。

高いところにPCを保管してないので壊れる可能性は低いと思うのですが、隣の棚に[ガリレオ温度計](https://www.nitori-net.jp/ec/product/8110734s/)を置いているので、液体にやられる可能性が0では無いといったところです。

よろしくお願いします。

**Comment by hansuoi** [comment]
@Schwarzschi1d 
いえいえ、むしろお休み中にすみません。
では、帰省中の旨を部長に伝えておくので、ご実家でゆっくりお休みなさってくださいな。
PCがぶっ壊れてたら新品のおnewをもらいましょう！
